//account
export const SET_LANGUAGE_SUCCESS = "SET_LANGUAGE_SUCCESS";
export const GET_DRIVER_INFO_SUCCESS = "GET_DRIVER_INFO_SUCCESS";
export const CHANGE_DRIVER_NAME_AVATAR_SUCCESS =
  "CHANGE_DRIVER_NAME_AVATAR_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const CLEAR_LOGIN_MESSAGE_SUCCESS = "CLEAR_LOGIN_MESSAGE_SUCCESS";

//order
export const GET_DRIVER_ORDER_LIST = "GET_DRIVER_ORDER_LIST";
export const SEARCH_DRIVER_ORDER = "SEARCH_DRIVER_ORDER";
export const SEARCH_DRIVER_ORDER_START = "SEARCH_DRIVER_ORDER_START";
export const CHANGE_ORDER_STATE_SUCCESS = "CHANGE_ORDER_STATE_SUCCESS";
